version: '3.3'

services:
  remembrall:
    image: $IMAGE
    ports:
      - "8080:8080"
    depends_on:
      - maria-db

  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/remembrall.de/fullchain.pem:/etc/nginx/certs/remembrall.pem
      - /etc/letsencrypt/live/remembrall.de/privkey.pem:/etc/nginx/certs/remembrall.key
    depends_on:
      - remembrall 

  maria-db:
    image: mariadb:10.4.8
    environment:
      MYSQL_DATABASE: remembrall
      MYSQL_USER: remembrall
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - maria-db-storage:/var/lib/mysql

volumes:
  maria-db-storage:
