version: '3.3'

services:
  rmbr:
    image: $IMAGE
    ports:
      - "8080:8080"
    depends_on:
      - maria-db

  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rmbr 

  maria-db:
    image: mariadb:10.4.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rmbr
      MYSQL_USER: rmbr
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - maria-db-storage:/var/lib/mysql

volumes:
  maria-db-storage:
