version: '3.3'

services:
  remembrall:
    image: $IMAGE
    restart: always
    depends_on:
      - maria-db
      - redis
    volumes:
      - /data/firebase/remembrall-firebase.json:/data/firebase/remembrall-firebase.json
      - /data/mail/mail.conf:/data/mail/mail.conf

  nginx:
    image: nginx:1.18.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/remembrall.de/fullchain.pem:/etc/nginx/certs/remembrall.pem
      - /etc/letsencrypt/live/remembrall.de/privkey.pem:/etc/nginx/certs/remembrall.key
    depends_on:
      - remembrall

  maria-db:
    image: mariadb:10.4.8
    restart: always
    environment:
      MYSQL_DATABASE: remembrall
      MYSQL_USER: remembrall
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3006"
    volumes:
      - maria-db-storage:/var/lib/mysql
  
  redis:
    image: redis:6.0.5
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  maria-db-storage:

